apiVersion: v1
kind: Service
metadata:
  name: adnan-service
  labels:
    app: adnan
spec:
  selector:
    app: adnan
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 5000
      targetPort: 5000